[package]
name = "traveller_diary"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_extras = "0.31.1"
anyhow = "1.0.82"
config = ">=0.15.11"
chrono = ">=0.4.40"
refinery = { version = ">=0.8.16", features = ["rusqlite"] }
rusqlite = { version = ">=0.30.0", features = ["bundled"] }
proptest = ">=1.0.0"
log = "0.4.32"
