[package]
name = "traveller_diary"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = ">=1.0.82"
config = ">=0.15.11"
chrono = ">=0.4.40"
refinery = { version = ">=0.8.16", features = ["rusqlite"] }
rusqlite = { version = ">=0.30.0", features = ["bundled"] }
proptest = ">=1.0.0"
log = ">=0.4.32"
rust-embed = ">=8.11.0"
rand = "0.9.4"
slint = { git = "https://github.com/slint-ui/slint", rev="be067e1", features = ["gettext"]}
image = "0.25.10"

[build-dependencies]
slint-build = { git = "https://github.com/slint-ui/slint", rev="be067e1"}

[profile.release]
codegen-units = 1
lto = true
