import { ScrollView } from "std-widgets.slint";
import { GridViewSettings } from "common.slint";

export struct TravelItem { cover: image, name: string, country: string, city: string, date: string, tags: [string]}

export global TravelViewProps {
    in property <[TravelItem]> travels;
}

export component TravelView {
    ScrollView {
        horizontal-scrollbar-policy: always-off;

        FlexboxLayout {
            spacing: 10px;
            padding: 15px;
            flex-wrap: wrap;

            for travel in TravelViewProps.travels: Rectangle {
                drop-shadow-color: gray;
                drop-shadow-offset-x: 2px;
                drop-shadow-offset-y: 3px;
                drop-shadow-blur: 5px;
                min-width: GridViewSettings.min-el-width;
                max-width: GridViewSettings.max-el-width;
                border-radius: 4px;
                border-color: black;
                border-width: 1px;
                background: gray;

                VerticalLayout {
                    spacing: 3px;
                    alignment: center;
                    cross-axis-alignment: center;

                    Image {
                        width: 90%;
                        padding: 10px;
                        image-fit: contain;
                        source: travel.cover;
                    }

                    Text {
                        text: travel.name;
                    }

                    Text {
                        text: travel.country;
                    }

                    Text {
                        text: travel.city;
                    }

                    Text {
                        text: travel.date;
                    }

                    HorizontalLayout {
                        spacing: 3px;

                        for tag in travel.tags: Rectangle {
                            background: yellow;
                            border-radius: 4px;
                            VerticalLayout {
                                padding: 4px;

                                Text {
                                    text: "#"+tag;
                                    color: black;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
